# Form implementation generated from reading ui file 'contract_text_view.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContractView(object):
    def setupUi(self, ContractView):
        ContractView.setObjectName("ContractView")
        ContractView.resize(457, 588)
        self.verticalLayoutWidget = QtWidgets.QWidget(ContractView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 441, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(ContractView)
        QtCore.QMetaObject.connectSlotsByName(ContractView)

    def retranslateUi(self, ContractView):
        _translate = QtCore.QCoreApplication.translate
        ContractView.setWindowTitle(_translate("ContractView", "Form"))
        self.label.setText(_translate("ContractView", "This is the Contract:"))
