# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KComm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KComm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bKComm.proto\"\x1d\n\x0bInbound_Mac\x12\x0e\n\x06MacStr\x18\x01 \x01(\t\"\x1f\n\x0cMac_Response\x12\x0f\n\x07MacResp\x18\x01 \x01(\t2;\n\x05KComm\x12\x32\n\x11Transfer_Macaroon\x12\x0c.Inbound_Mac\x1a\r.Mac_Response\"\x00\x62\x06proto3')
)




_INBOUND_MAC = _descriptor.Descriptor(
  name='Inbound_Mac',
  full_name='Inbound_Mac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MacStr', full_name='Inbound_Mac.MacStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=44,
)


_MAC_RESPONSE = _descriptor.Descriptor(
  name='Mac_Response',
  full_name='Mac_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MacResp', full_name='Mac_Response.MacResp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Inbound_Mac'] = _INBOUND_MAC
DESCRIPTOR.message_types_by_name['Mac_Response'] = _MAC_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inbound_Mac = _reflection.GeneratedProtocolMessageType('Inbound_Mac', (_message.Message,), dict(
  DESCRIPTOR = _INBOUND_MAC,
  __module__ = 'KComm_pb2'
  # @@protoc_insertion_point(class_scope:Inbound_Mac)
  ))
_sym_db.RegisterMessage(Inbound_Mac)

Mac_Response = _reflection.GeneratedProtocolMessageType('Mac_Response', (_message.Message,), dict(
  DESCRIPTOR = _MAC_RESPONSE,
  __module__ = 'KComm_pb2'
  # @@protoc_insertion_point(class_scope:Mac_Response)
  ))
_sym_db.RegisterMessage(Mac_Response)



_KCOMM = _descriptor.ServiceDescriptor(
  name='KComm',
  full_name='KComm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=79,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='Transfer_Macaroon',
    full_name='KComm.Transfer_Macaroon',
    index=0,
    containing_service=None,
    input_type=_INBOUND_MAC,
    output_type=_MAC_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KCOMM)

DESCRIPTOR.services_by_name['KComm'] = _KCOMM

# @@protoc_insertion_point(module_scope)
