# Form implementation generated from reading ui file 'load_contract_form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadContractForm(object):
    def setupUi(self, LoadContractForm):
        LoadContractForm.setObjectName("LoadContractForm")
        LoadContractForm.resize(463, 354)
        self.load_contract_formWidget = QtWidgets.QWidget(LoadContractForm)
        self.load_contract_formWidget.setGeometry(QtCore.QRect(20, 70, 391, 121))
        self.load_contract_formWidget.setObjectName("load_contract_formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.load_contract_formWidget)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setObjectName("formLayout")
        self.load_contract_label_2 = QtWidgets.QLabel(self.load_contract_formWidget)
        self.load_contract_label_2.setObjectName("load_contract_label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.load_contract_label_2)
        self.load_contract_contractComboBox = QtWidgets.QComboBox(self.load_contract_formWidget)
        self.load_contract_contractComboBox.setObjectName("load_contract_contractComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.load_contract_contractComboBox)
        self.load_contract_buttonBox = QtWidgets.QDialogButtonBox(self.load_contract_formWidget)
        self.load_contract_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.load_contract_buttonBox.setObjectName("load_contract_buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.load_contract_buttonBox)
        self.load_contract_bottom_label = QtWidgets.QLabel(self.load_contract_formWidget)
        self.load_contract_bottom_label.setText("")
        self.load_contract_bottom_label.setObjectName("load_contract_bottom_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.load_contract_bottom_label)
        self.load_contract_label = QtWidgets.QLabel(LoadContractForm)
        self.load_contract_label.setGeometry(QtCore.QRect(20, 20, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_contract_label.setFont(font)
        self.load_contract_label.setObjectName("load_contract_label")
        self.load_contract_bottom_Label = QtWidgets.QLabel(LoadContractForm)
        self.load_contract_bottom_Label.setGeometry(QtCore.QRect(20, 260, 389, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_contract_bottom_Label.setFont(font)
        self.load_contract_bottom_Label.setText("")
        self.load_contract_bottom_Label.setObjectName("load_contract_bottom_Label")

        self.retranslateUi(LoadContractForm)
        QtCore.QMetaObject.connectSlotsByName(LoadContractForm)

    def retranslateUi(self, LoadContractForm):
        _translate = QtCore.QCoreApplication.translate
        LoadContractForm.setWindowTitle(_translate("LoadContractForm", "Good Form"))
        self.load_contract_label_2.setText(_translate("LoadContractForm", "Contract"))
        self.load_contract_label.setText(_translate("LoadContractForm", "Pick Contract:"))
