# Form implementation generated from reading ui file 'service_number_form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServiceNumberForm(object):
    def setupUi(self, ServiceNumberForm):
        ServiceNumberForm.setObjectName("ServiceNumberForm")
        ServiceNumberForm.resize(389, 300)
        self.sn_entry_form_Widget = QtWidgets.QWidget(ServiceNumberForm)
        self.sn_entry_form_Widget.setGeometry(QtCore.QRect(10, 70, 371, 121))
        self.sn_entry_form_Widget.setObjectName("sn_entry_form_Widget")
        self.formLayout = QtWidgets.QFormLayout(self.sn_entry_form_Widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.sn_entry_service_number_Label = QtWidgets.QLabel(self.sn_entry_form_Widget)
        self.sn_entry_service_number_Label.setObjectName("sn_entry_service_number_Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sn_entry_service_number_Label)
        self.sn_entry_service_number_LineEdit = QtWidgets.QLineEdit(self.sn_entry_form_Widget)
        self.sn_entry_service_number_LineEdit.setObjectName("sn_entry_service_number_LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sn_entry_service_number_LineEdit)
        self.sn_entry_description_Label = QtWidgets.QLabel(self.sn_entry_form_Widget)
        self.sn_entry_description_Label.setObjectName("sn_entry_description_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sn_entry_description_Label)
        self.sn_entry_description_LineEdit = QtWidgets.QLineEdit(self.sn_entry_form_Widget)
        self.sn_entry_description_LineEdit.setObjectName("sn_entry_description_LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sn_entry_description_LineEdit)
        self.sn_entry_ButtonBox = QtWidgets.QDialogButtonBox(self.sn_entry_form_Widget)
        self.sn_entry_ButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.sn_entry_ButtonBox.setObjectName("sn_entry_ButtonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sn_entry_ButtonBox)
        self.sn_entry_status_LineEdit = QtWidgets.QLineEdit(self.sn_entry_form_Widget)
        self.sn_entry_status_LineEdit.setObjectName("sn_entry_status_LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sn_entry_status_LineEdit)
        self.sn_status_Label = QtWidgets.QLabel(self.sn_entry_form_Widget)
        self.sn_status_Label.setObjectName("sn_status_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sn_status_Label)
        self.sn_entry_form_Label = QtWidgets.QLabel(ServiceNumberForm)
        self.sn_entry_form_Label.setGeometry(QtCore.QRect(10, 30, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sn_entry_form_Label.setFont(font)
        self.sn_entry_form_Label.setObjectName("sn_entry_form_Label")
        self.sn_bottem_Label = QtWidgets.QLabel(ServiceNumberForm)
        self.sn_bottem_Label.setGeometry(QtCore.QRect(20, 210, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sn_bottem_Label.setFont(font)
        self.sn_bottem_Label.setText("")
        self.sn_bottem_Label.setObjectName("sn_bottem_Label")

        self.retranslateUi(ServiceNumberForm)
        QtCore.QMetaObject.connectSlotsByName(ServiceNumberForm)
        ServiceNumberForm.setTabOrder(self.sn_entry_service_number_LineEdit, self.sn_entry_description_LineEdit)
        ServiceNumberForm.setTabOrder(self.sn_entry_description_LineEdit, self.sn_entry_status_LineEdit)

    def retranslateUi(self, ServiceNumberForm):
        _translate = QtCore.QCoreApplication.translate
        ServiceNumberForm.setWindowTitle(_translate("ServiceNumberForm", "Form"))
        self.sn_entry_service_number_Label.setText(_translate("ServiceNumberForm", "Service Number"))
        self.sn_entry_description_Label.setText(_translate("ServiceNumberForm", "Description"))
        self.sn_status_Label.setText(_translate("ServiceNumberForm", "Status"))
        self.sn_entry_form_Label.setText(_translate("ServiceNumberForm", "Service Number Entry:"))
