# Form implementation generated from reading ui file 'service_number_entry.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_service_number_form(object):
    def setupUi(self, service_number_form):
        service_number_form.setObjectName("service_number_form")
        service_number_form.resize(457, 300)
        self.service_entry_formWidget = QtWidgets.QWidget(service_number_form)
        self.service_entry_formWidget.setGeometry(QtCore.QRect(9, 60, 371, 161))
        self.service_entry_formWidget.setObjectName("service_entry_formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.service_entry_formWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.service_entery_name_Label = QtWidgets.QLabel(self.service_entry_formWidget)
        self.service_entery_name_Label.setObjectName("service_entery_name_Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.service_entery_name_Label)
        self.service_entry_name_LineEdit = QtWidgets.QLineEdit(self.service_entry_formWidget)
        self.service_entry_name_LineEdit.setObjectName("service_entry_name_LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.service_entry_name_LineEdit)
        self.service_entry_part_number_Label = QtWidgets.QLabel(self.service_entry_formWidget)
        self.service_entry_part_number_Label.setObjectName("service_entry_part_number_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.service_entry_part_number_Label)
        self.service__entry_pn_entry_part_number_LineEdit = QtWidgets.QLineEdit(self.service_entry_formWidget)
        self.service__entry_pn_entry_part_number_LineEdit.setObjectName("service__entry_pn_entry_part_number_LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.service__entry_pn_entry_part_number_LineEdit)
        self.service_entry_description_Label = QtWidgets.QLabel(self.service_entry_formWidget)
        self.service_entry_description_Label.setObjectName("service_entry_description_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.service_entry_description_Label)
        self.service_entry_description_LineEdit = QtWidgets.QLineEdit(self.service_entry_formWidget)
        self.service_entry_description_LineEdit.setObjectName("service_entry_description_LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.service_entry_description_LineEdit)
        self.service_entry_buttonBox = QtWidgets.QDialogButtonBox(self.service_entry_formWidget)
        self.service_entry_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.service_entry_buttonBox.setObjectName("service_entry_buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.service_entry_buttonBox)
        self.service_entry_form_label = QtWidgets.QLabel(service_number_form)
        self.service_entry_form_label.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.service_entry_form_label.setObjectName("service_entry_form_label")

        self.retranslateUi(service_number_form)
        QtCore.QMetaObject.connectSlotsByName(service_number_form)

    def retranslateUi(self, service_number_form):
        _translate = QtCore.QCoreApplication.translate
        service_number_form.setWindowTitle(_translate("service_number_form", "Form"))
        self.service_entery_name_Label.setText(_translate("service_number_form", "Name"))
        self.service_entry_part_number_Label.setText(_translate("service_number_form", "Service Number"))
        self.service_entry_description_Label.setText(_translate("service_number_form", "Description"))
        self.service_entry_form_label.setText(_translate("service_number_form", "Service Number Entry"))
